import type { GeneralGardenTask } from '@/lib/types'

/**
 * Kuraterede sæson-tips der vises som inspiration på dashboard og kalender.
 * Ikke bruger-data — gælder for alle og opdateres ikke per bruger.
 */
export const GENERAL_GARDEN_TASKS: GeneralGardenTask[] = [
  {
    id: 'gen_001',
    title: 'Forspir chili, aubergine og tomat',
    description: 'Chili og aubergine har lang udviklingstid — start allerede nu.',
    month: 2,
    category: 'forspiring',
    priority: 'medium',
    recurrence: 'yearly',
    sourceType: 'curated',
    linkedGuideIds: ['guide_chili', 'guide_tomat'],
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
  },
  {
    id: 'gen_002',
    title: 'Klargør jord og drivhus',
    description: 'Varm jorden op og luft ud. Tjek for huller i drivhus-plast.',
    month: 3,
    category: 'klargoering',
    priority: 'medium',
    recurrence: 'yearly',
    sourceType: 'curated',
    linkedGuideIds: [],
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
  },
  {
    id: 'gen_003',
    title: 'Prikl ud, så direkte, begynd hærdning',
    description: 'April er månedens store rutsjebane — alt sker samtidig.',
    month: 4,
    category: 'saaning',
    priority: 'high',
    recurrence: 'yearly',
    sourceType: 'curated',
    linkedGuideIds: [],
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
  },
  {
    id: 'gen_004',
    title: 'Udplant frostfølsomme planter',
    description: 'Efter isdamerne (midt-slut maj) kan tomater, agurker og chili ud.',
    month: 5,
    category: 'udplantning',
    priority: 'high',
    recurrence: 'yearly',
    sourceType: 'curated',
    linkedGuideIds: [],
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
  },
  {
    id: 'gen_005',
    title: 'Vand, gød og bind planter op',
    description: 'Juni er væksttid — regelmæssig pleje er alt.',
    month: 6,
    category: 'vedligehold',
    priority: 'medium',
    recurrence: 'yearly',
    sourceType: 'curated',
    linkedGuideIds: [],
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
  },
  {
    id: 'gen_006',
    title: 'Høst og vedligehold',
    description: 'Juli-august er høsttid. Pluk ofte for at holde planterne i produktion.',
    month: 7,
    category: 'hoest',
    priority: 'medium',
    recurrence: 'yearly',
    sourceType: 'curated',
    linkedGuideIds: [],
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
  },
  {
    id: 'gen_007',
    title: 'Saml frø til næste år',
    description: 'August er perfekt tid til at gemme frø fra dine bedste planter.',
    month: 8,
    category: 'froesamling',
    priority: 'low',
    recurrence: 'yearly',
    sourceType: 'curated',
    linkedGuideIds: [],
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
  },
  {
    id: 'gen_008',
    title: 'Plant forårsløg og del stauder',
    description: 'September er den bedste måned til løg — og staudedeling.',
    month: 9,
    category: 'plantning',
    priority: 'medium',
    recurrence: 'yearly',
    sourceType: 'curated',
    linkedGuideIds: [],
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
  },
  {
    id: 'gen_009',
    title: 'Plant træer og buske',
    description: 'Oktober er træ-plantnings-måneden. Jorden er varm og fugtig.',
    month: 10,
    category: 'plantning',
    priority: 'low',
    recurrence: 'yearly',
    sourceType: 'curated',
    linkedGuideIds: [],
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
  },
  {
    id: 'gen_010',
    title: 'Vinterklargøring',
    description: 'Tøm krukker, dæk følsomme planter, rens værktøj.',
    month: 11,
    category: 'vinterklargoering',
    priority: 'medium',
    recurrence: 'yearly',
    sourceType: 'curated',
    linkedGuideIds: [],
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
  },
  {
    id: 'gen_011',
    title: 'Planlæg næste sæson',
    description: 'December er planlægningsmåned. Gennemgå frøbank, bestil nyt.',
    month: 12,
    category: 'planlaegning',
    priority: 'low',
    recurrence: 'yearly',
    sourceType: 'curated',
    linkedGuideIds: [],
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
  },
  {
    id: 'gen_012',
    title: 'Planlæg sæson, gennemgå frø',
    description: 'Januar er rolig — perfekt til at drømme og bestille.',
    month: 1,
    category: 'planlaegning',
    priority: 'low',
    recurrence: 'yearly',
    sourceType: 'curated',
    linkedGuideIds: [],
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
  },
]
