/**
 * Demo-frøbank: kuraterede demo-data der vises når brugeren ikke
 * har egne items (anonymt eller før første tilføjelse). Matcher
 * præcis seed.sql så designet er konsistent på tværs af kalender
 * og /froebank-siden.
 *
 * Når brugeren logger ind og tilføjer egne frø, skifter visningen
 * automatisk til deres rigtige data.
 */

import type { InventoryItem, Plant } from './types'

export const DEMO_INVENTORY: InventoryItem[] = [
  {
    id: 'demo-inv-tomat-cherry',
    userId: 'demo',
    name: 'Tomat',
    variety: 'Cherry Sweetie',
    latinName: 'Solanum lycopersicum',
    supplier: 'Frøsalg',
    primaryCategoryId: 'fro',
    subcategoryId: 'groentsager',
    seedCount: 12,
    seedsSown: 5,
    seedsRemaining: 7,
    purchaseYear: 2026,
    sowingMonths: [3, 4],
    sowingDepthMm: 5,
    preCultivation: true,
    plantingOutMonths: [5, 6],
    harvestMonths: [7, 8, 9],
    light: 'full_sun',
    water: 'high',
    germinationDays: '7-14 dage',
    plantSpacing: '50 cm',
    growingLocations: ['drivhus', 'friland'],
    status: 'i_froebank',
    isFavorite: true,
    isPinned: false,
    imageIds: [],
    primaryImageId: '/images/frokort/cherrytomat.png',
    linkedPlantIds: [],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-04-15T00:00:00Z',
  },
  {
    id: 'demo-inv-chili',
    userId: 'demo',
    name: 'Chili',
    variety: 'Habanero Orange',
    latinName: 'Capsicum chinense',
    supplier: 'Solhatten',
    primaryCategoryId: 'fro',
    subcategoryId: 'groentsager',
    seedCount: 8,
    seedsSown: 1,
    seedsRemaining: 7,
    purchaseYear: 2026,
    sowingMonths: [2, 3],
    sowingDepthMm: 5,
    preCultivation: true,
    plantingOutMonths: [5, 6],
    harvestMonths: [8, 9, 10],
    light: 'full_sun',
    water: 'regular',
    germinationDays: '14-21 dage',
    plantSpacing: '40 cm',
    growingLocations: ['drivhus'],
    status: 'i_froebank',
    isFavorite: false,
    isPinned: false,
    imageIds: [],
    primaryImageId: '/images/frokort/chili-habanero-orange.png',
    linkedPlantIds: [],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-02-25T00:00:00Z',
  },
  {
    id: 'demo-inv-peberfrugt',
    userId: 'demo',
    name: 'Peberfrugt',
    variety: 'California Wonder',
    latinName: 'Capsicum annuum',
    supplier: 'Frøsalg',
    primaryCategoryId: 'fro',
    subcategoryId: 'groentsager',
    seedCount: 10,
    seedsSown: 0,
    seedsRemaining: 10,
    purchaseYear: 2026,
    sowingMonths: [3],
    sowingDepthMm: 5,
    preCultivation: true,
    plantingOutMonths: [5, 6],
    harvestMonths: [8, 9],
    light: 'full_sun',
    water: 'regular',
    germinationDays: '10-14 dage',
    plantSpacing: '40 cm',
    growingLocations: ['drivhus'],
    status: 'i_froebank',
    isFavorite: false,
    isPinned: false,
    imageIds: [],
    primaryImageId: '/images/frokort/peberfrugt-california-wonder.png',
    linkedPlantIds: [],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'demo-inv-peberfrugt-corno',
    userId: 'demo',
    name: 'Peberfrugt',
    variety: 'Corno di Toro Rosso',
    latinName: "Capsicum annuum 'Corno di Toro Rosso'",
    supplier: 'Frøsalg',
    primaryCategoryId: 'fro',
    subcategoryId: 'groentsager',
    seedCount: 8,
    seedsSown: 0,
    seedsRemaining: 8,
    purchaseYear: 2026,
    sowingMonths: [3],
    sowingDepthMm: 5,
    preCultivation: true,
    plantingOutMonths: [5, 6],
    harvestMonths: [8, 9, 10],
    light: 'full_sun',
    water: 'regular',
    germinationDays: '10-14 dage',
    plantSpacing: '40 cm',
    growingLocations: ['drivhus'],
    status: 'i_froebank',
    isFavorite: false,
    isPinned: false,
    imageIds: [],
    primaryImageId: '/images/frokort/peberfrugt-corno-di-toro-rosso.png',
    guideId: 'peberfrugt-corno-di-toro-rosso',
    linkedPlantIds: [],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-06-06T00:00:00Z',
  },
  {
    id: 'demo-inv-squash',
    userId: 'demo',
    name: 'Squash',
    variety: 'Eight Ball',
    latinName: 'Cucurbita pepo',
    supplier: 'Solhatten',
    primaryCategoryId: 'fro',
    subcategoryId: 'groentsager',
    seedCount: 10,
    seedsSown: 0,
    seedsRemaining: 10,
    purchaseYear: 2026,
    sowingMonths: [4, 5],
    sowingDepthMm: 20,
    preCultivation: true,
    plantingOutMonths: [5, 6],
    harvestMonths: [7, 8, 9],
    light: 'full_sun',
    water: 'high',
    germinationDays: '7-10 dage',
    plantSpacing: '90 cm',
    growingLocations: ['friland', 'drivhus'],
    status: 'i_froebank',
    isFavorite: false,
    isPinned: false,
    imageIds: [],
    primaryImageId: '/images/frokort/squash-eight-ball.png',
    linkedPlantIds: [],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'demo-inv-stangboenne',
    userId: 'demo',
    name: 'Stangbønne',
    variety: 'Cobra',
    latinName: 'Phaseolus vulgaris',
    supplier: 'Frøsalg',
    primaryCategoryId: 'fro',
    subcategoryId: 'groentsager',
    seedCount: 24,
    seedsSown: 18,
    seedsRemaining: 6,
    purchaseYear: 2024,
    sowingMonths: [5, 6],
    sowingDepthMm: 25,
    preCultivation: false,
    plantingOutMonths: [],
    harvestMonths: [8, 9],
    light: 'full_sun',
    water: 'regular',
    germinationDays: '7-14 dage',
    plantSpacing: '15 cm',
    growingLocations: ['friland'],
    status: 'i_froebank',
    isFavorite: false,
    isPinned: false,
    imageIds: [],
    primaryImageId: '/images/frokort/stangboenne-cobra.png',
    linkedPlantIds: [],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-05-05T00:00:00Z',
  },
  {
    id: 'demo-inv-agurk',
    userId: 'demo',
    name: 'Agurk',
    variety: 'Marketmore',
    latinName: 'Cucumis sativus',
    supplier: 'Solhatten',
    primaryCategoryId: 'fro',
    subcategoryId: 'groentsager',
    seedCount: 15,
    seedsSown: 1,
    seedsRemaining: 14,
    purchaseYear: 2026,
    sowingMonths: [4, 5],
    sowingDepthMm: 10,
    preCultivation: true,
    plantingOutMonths: [6],
    harvestMonths: [7, 8, 9],
    light: 'full_sun',
    water: 'high',
    germinationDays: '5-10 dage',
    plantSpacing: '40 cm',
    growingLocations: ['drivhus'],
    status: 'i_froebank',
    isFavorite: false,
    isPinned: false,
    imageIds: [],
    primaryImageId: '/images/frokort/agurk-marketmore.png',
    linkedPlantIds: [],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-04-10T00:00:00Z',
  },
  {
    id: 'demo-inv-salat',
    userId: 'demo',
    name: 'Salat',
    variety: 'Crispy Mint',
    latinName: 'Lactuca sativa',
    supplier: 'Solhatten',
    primaryCategoryId: 'fro',
    subcategoryId: 'groentsager',
    seedCount: 200,
    seedsSown: 11,
    seedsRemaining: 189,
    purchaseYear: 2024,
    sowingMonths: [3, 4, 5, 6, 7, 8],
    sowingDepthMm: 5,
    preCultivation: false,
    plantingOutMonths: [],
    harvestMonths: [5, 6, 7, 8, 9],
    light: 'partial_shade',
    water: 'regular',
    germinationDays: '7-10 dage',
    plantSpacing: '25 cm',
    growingLocations: ['friland', 'drivhus'],
    status: 'i_froebank',
    isFavorite: false,
    isPinned: true,
    imageIds: [],
    primaryImageId: '/images/frokort/salat-crispy-mint.png',
    linkedPlantIds: [],
    // Senest tilføjet — driver "Du tilføjede Salat Crispy Mint …"-
    // aktivitetslinjen. Sat 2 dage før dagens dato i demo.
    createdAt: new Date(Date.now() - 2 * 86_400_000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 86_400_000).toISOString(),
  },
]

export const DEMO_PLANTS: Plant[] = [
  {
    id: 'demo-plant-tomat-san-marzano',
    userId: 'demo',
    name: 'Tomat',
    variety: 'San Marzano',
    status: 'klar_til_udplantning',
    location: 'Vindueskarm',
    sowDate: '2026-03-15',
    plantingOutDate: null,
    quantity: 6,
    imageIds: [],
    primaryImageId: '/images/plantekort/tomat-san-marzano.jpg',
    logIds: [],
    isArchived: false,
    createdAt: '2026-03-15T00:00:00Z',
    updatedAt: '2026-05-01T00:00:00Z',
  },
  {
    id: 'demo-plant-peberfrugt-corno',
    userId: 'demo',
    name: 'Peberfrugt',
    variety: 'Corno di Toro Rosso',
    status: 'i_vaekst',
    location: 'Drivhus',
    sowDate: '2026-03-10',
    plantingOutDate: '2026-05-20',
    quantity: 4,
    imageIds: [],
    primaryImageId: '/images/plantekort/peberfrugt-corno-di-toro-rosso.jpg',
    guideId: 'peberfrugt-corno-di-toro-rosso',
    logIds: [],
    isArchived: false,
    createdAt: '2026-03-10T00:00:00Z',
    updatedAt: '2026-06-06T00:00:00Z',
  },
  {
    id: 'demo-plant-sukkeraert',
    userId: 'demo',
    name: 'Sukkerært',
    variety: 'Sugar Snap',
    status: 'spirer',
    location: 'Have, sydbed',
    sowDate: '2026-04-10',
    plantingOutDate: null,
    quantity: 12,
    imageIds: [],
    primaryImageId: '/images/plantekort/sukkeraert-sugar-snap.jpg',
    logIds: [],
    isArchived: false,
    createdAt: '2026-04-10T00:00:00Z',
    updatedAt: '2026-04-20T00:00:00Z',
  },
  {
    id: 'demo-plant-chili',
    userId: 'demo',
    name: 'Chili',
    variety: 'Habanero Orange',
    status: 'i_vaekst',
    location: 'Drivhus',
    sowDate: '2026-02-20',
    plantingOutDate: null,
    quantity: 5,
    imageIds: [],
    primaryImageId: '/images/plantekort/chili-habanero-orange.jpg',
    logIds: [],
    isArchived: false,
    createdAt: '2026-02-20T00:00:00Z',
    updatedAt: '2026-05-01T00:00:00Z',
  },
  {
    id: 'demo-plant-agurk',
    userId: 'demo',
    name: 'Agurk',
    variety: 'Marketmore',
    status: 'i_vaekst',
    location: 'Drivhus',
    sowDate: '2026-04-10',
    plantingOutDate: null,
    quantity: 14,
    imageIds: [],
    primaryImageId: '/images/plantekort/agurk-marketmore.png',
    logIds: [],
    isArchived: false,
    createdAt: '2026-04-10T00:00:00Z',
    updatedAt: '2026-05-01T00:00:00Z',
  },
  {
    id: 'demo-plant-stangboenne',
    userId: 'demo',
    name: 'Stangbønne',
    variety: 'Cobra',
    status: 'spirer',
    location: 'Have, sydbed',
    sowDate: '2026-05-05',
    plantingOutDate: null,
    quantity: 6,
    imageIds: [],
    primaryImageId: '/images/plantekort/stangboenne-cobra.jpg',
    logIds: [],
    isArchived: false,
    createdAt: '2026-05-05T00:00:00Z',
    updatedAt: '2026-05-12T00:00:00Z',
  },
  {
    id: 'demo-plant-dild',
    userId: 'demo',
    name: 'Dild',
    variety: 'Bouquet',
    status: 'i_vaekst',
    location: 'Krydderurte-bed',
    sowDate: '2026-04-15',
    plantingOutDate: null,
    quantity: 8,
    imageIds: [],
    primaryImageId: '/images/plantekort/dild-bouquet.jpg',
    logIds: [],
    isArchived: false,
    createdAt: '2026-04-15T00:00:00Z',
    updatedAt: '2026-05-01T00:00:00Z',
  },
  {
    id: 'demo-plant-dahlia',
    userId: 'demo',
    name: 'Dahlia',
    variety: 'Café au Lait',
    status: 'planlagt',
    location: null,
    sowDate: null,
    plantingOutDate: null,
    quantity: 3,
    imageIds: [],
    primaryImageId: '/images/plantekort/dahlia-cafe-au-lait.jpg',
    logIds: [],
    isArchived: false,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
]
