/**
 * Mock data til første version.
 *
 * TODO (database): Udskift hele denne fil med Supabase-queries når DB er koblet op.
 * Alle funktioner her returnerer plain data - ingen Promise. Senere wrap i async.
 */

import type {
  Profile, InventoryItem, Plant, PlantLog, CalendarTask, GeneralGardenTask,
  Guide, CommunityGroup, CommunityMembership, Idea, MediaAsset,
  NotificationPreference, ProgressState, Subcategory,
} from './types'

// ============================================
// Demo bruger
// ============================================

export const MOCK_USER_ID = 'user_demo_001'

export const MOCK_PROFILE: Profile = {
  id: MOCK_USER_ID,
  username: 'Demo Gartner',
  email: 'demo@potalot.app',
  avatarUrl: null,
  userMode: 'afslappet',
  onboarded: true, // Sættes til false første gang for at teste onboarding
  createdAt: '2026-01-01T00:00:00Z',
  updatedAt: '2026-04-24T00:00:00Z',
}

// ============================================
// Frøbank
// ============================================

export const MOCK_INVENTORY: InventoryItem[] = [
  {
    id: 'inv_001',
    userId: MOCK_USER_ID,
    name: 'Tomat',
    variety: 'San Marzano',
    supplier: 'Impecta',
    primaryCategoryId: 'fro',
    subcategoryId: 'groentsager',
    quantity: 35,
    purchaseDate: '2026-02-01',
    expiryDate: '2029-02-01',
    notes: 'God til saucer, forspiring anbefales.',
    sowingMonths: [3, 4],
    sowingDepthMm: 5,
    preCultivation: true,
    plantingOutMonths: [5, 6],
    harvestMonths: [7, 8, 9],
    light: 'full_sun',
    water: 'regular',
    soil: 'Næringsrig, veldrænet',
    germinationTemperature: '20-25°C',
    germinationDays: '7-14',
    plantSpacing: '40-60 cm',
    rowSpacing: '60-80 cm',
    growingLocations: ['drivhus', 'hoejbed'],
    status: 'i_froebank',
    isFavorite: true,
    isPinned: false,
    imageIds: [],
    guideId: 'guide_tomat',
    linkedPlantIds: ['plant_001'],
    createdAt: '2026-02-01T10:00:00Z',
    updatedAt: '2026-04-10T10:00:00Z',
  },
  {
    id: 'inv_002',
    userId: MOCK_USER_ID,
    name: 'Jalapeño',
    variety: 'Early Jalapeño',
    supplier: 'Nordfrø',
    primaryCategoryId: 'fro',
    subcategoryId: 'groentsager',
    quantity: 20,
    purchaseDate: '2026-01-15',
    expiryDate: '2029-01-15',
    sowingMonths: [2, 3],
    sowingDepthMm: 5,
    preCultivation: true,
    plantingOutMonths: [5, 6],
    harvestMonths: [8, 9, 10],
    light: 'full_sun',
    water: 'regular',
    germinationTemperature: '22-28°C',
    germinationDays: '10-21',
    plantSpacing: '40-50 cm',
    growingLocations: ['drivhus', 'krukke'],
    status: 'saaet',
    isFavorite: true,
    isPinned: true,
    imageIds: [],
    guideId: 'guide_chili',
    linkedPlantIds: ['plant_002'],
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-03-15T10:00:00Z',
  },
  {
    id: 'inv_003',
    userId: MOCK_USER_ID,
    name: 'Basilikum',
    variety: 'Genovese',
    supplier: 'DT Brown',
    primaryCategoryId: 'fro',
    subcategoryId: 'krydderurter',
    quantity: 50,
    sowingMonths: [3, 4, 5],
    sowingDepthMm: 0,                  // Overfladen
    preCultivation: true,
    plantingOutMonths: [5, 6],
    harvestMonths: [6, 7, 8, 9],
    light: 'full_sun',
    water: 'regular',
    growingLocations: ['vindueskarm', 'krukke', 'drivhus'],
    status: 'i_froebank',
    isFavorite: false,
    isPinned: false,
    imageIds: [],
    guideId: null,
    linkedPlantIds: [],
    createdAt: '2026-02-20T10:00:00Z',
    updatedAt: '2026-02-20T10:00:00Z',
  },
  {
    id: 'inv_004',
    userId: MOCK_USER_ID,
    name: 'Tulipan',
    variety: 'Queen of Night',
    supplier: 'Plantorama',
    primaryCategoryId: 'loeg',
    subcategoryId: 'blomster_fleraarige',
    quantity: 50,
    purchaseDate: '2025-09-15',
    sowingMonths: [9, 10, 11],
    sowingDepthMm: 150,
    preCultivation: false,
    plantingOutMonths: [],
    harvestMonths: [],
    light: 'full_sun',
    water: 'low',
    growingLocations: ['friland', 'hoejbed'],
    status: 'i_jord',
    isFavorite: false,
    isPinned: false,
    imageIds: [],
    linkedPlantIds: [],
    createdAt: '2025-09-15T10:00:00Z',
    updatedAt: '2025-10-10T10:00:00Z',
  },
  {
    id: 'inv_005',
    userId: MOCK_USER_ID,
    name: 'Rapini / vinterbroccoli',
    variety: null,
    supplier: 'Nelson Garden',
    primaryCategoryId: 'fro',
    subcategoryId: 'groentsager',
    quantity: 40,
    sowingMonths: [3, 4, 8],
    sowingDepthMm: 10,
    preCultivation: false,
    plantingOutMonths: [],
    harvestMonths: [6, 10, 11],
    light: 'full_sun',
    water: 'regular',
    growingLocations: ['hoejbed', 'friland'],
    status: 'saaet',
    isFavorite: false,
    isPinned: false,
    imageIds: [],
    linkedPlantIds: ['plant_003'],
    createdAt: '2026-03-01T10:00:00Z',
    updatedAt: '2026-03-28T10:00:00Z',
  },
  {
    id: 'inv_006',
    userId: MOCK_USER_ID,
    name: 'Blåbær',
    variety: 'Patriot',
    primaryCategoryId: 'buske',
    subcategoryId: 'baer',
    quantity: 2,
    purchaseDate: '2025-04-01',
    sowingMonths: [],
    sowingDepthMm: 0,
    preCultivation: false,
    plantingOutMonths: [4, 5],
    harvestMonths: [7, 8],
    light: 'full_sun',
    water: 'regular',
    soil: 'Sur jord (pH 4.5-5.5)',
    growingLocations: ['hoejbed', 'friland'],
    status: 'i_vaekst',
    isFavorite: true,
    isPinned: false,
    imageIds: [],
    linkedPlantIds: [],
    createdAt: '2025-04-01T10:00:00Z',
    updatedAt: '2026-04-01T10:00:00Z',
  },
  {
    id: 'inv_007',
    userId: MOCK_USER_ID,
    name: 'Kirsebærtræ',
    variety: 'Stevnsbær',
    primaryCategoryId: 'traeer',
    subcategoryId: 'frugt',
    quantity: 1,
    purchaseDate: '2024-03-15',
    sowingMonths: [],
    sowingDepthMm: 0,
    preCultivation: false,
    plantingOutMonths: [3, 4, 10, 11],
    harvestMonths: [7, 8],
    light: 'full_sun',
    water: 'regular',
    growingLocations: ['friland'],
    status: 'i_vaekst',
    isFavorite: false,
    isPinned: false,
    imageIds: [],
    linkedPlantIds: [],
    createdAt: '2024-03-15T10:00:00Z',
    updatedAt: '2026-04-01T10:00:00Z',
  },
  {
    id: 'inv_008',
    userId: MOCK_USER_ID,
    name: 'Passionsblomst',
    variety: null,
    primaryCategoryId: 'indkoebsliste',
    quantity: 1,
    sowingMonths: [],
    sowingDepthMm: 0,
    preCultivation: false,
    plantingOutMonths: [],
    harvestMonths: [],
    notes: 'Køb denne på forårsmarkedet',
    growingLocations: ['krukke'],
    status: 'i_froebank',
    isFavorite: false,
    isPinned: false,
    imageIds: [],
    linkedPlantIds: [],
    createdAt: '2026-03-10T10:00:00Z',
    updatedAt: '2026-03-10T10:00:00Z',
  },
]

// ============================================
// Mine planter
// ============================================

export const MOCK_PLANTS: Plant[] = [
  {
    id: 'plant_001',
    userId: MOCK_USER_ID,
    sourceElementId: 'inv_001',
    name: 'Tomat',
    variety: 'San Marzano',
    status: 'i_vaekst',
    location: 'Drivhus',
    sowDate: '2026-03-10',
    plantingOutDate: '2026-05-15',
    quantity: 6,
    imageIds: [],
    logIds: ['log_001', 'log_002', 'log_003'],
    guideId: 'guide_tomat',
    isArchived: false,
    createdAt: '2026-03-10T10:00:00Z',
    updatedAt: '2026-05-15T10:00:00Z',
  },
  {
    id: 'plant_002',
    userId: MOCK_USER_ID,
    sourceElementId: 'inv_002',
    name: 'Jalapeño',
    variety: 'Early Jalapeño',
    status: 'spirer',
    location: 'Vindueskarm',
    sowDate: '2026-03-15',
    quantity: 4,
    imageIds: [],
    logIds: ['log_004', 'log_005'],
    guideId: 'guide_chili',
    isArchived: false,
    createdAt: '2026-03-15T10:00:00Z',
    updatedAt: '2026-04-10T10:00:00Z',
  },
  {
    id: 'plant_003',
    userId: MOCK_USER_ID,
    sourceElementId: 'inv_005',
    name: 'Rapini / vinterbroccoli',
    variety: null,
    status: 'spirer',
    location: 'Højbed 2',
    sowDate: '2026-03-28',
    quantity: 12,
    imageIds: [],
    logIds: ['log_006'],
    isArchived: false,
    createdAt: '2026-03-28T10:00:00Z',
    updatedAt: '2026-04-20T10:00:00Z',
  },
  // Arkiveret plante fra sidste år — til sammenligning
  {
    id: 'plant_arch_001',
    userId: MOCK_USER_ID,
    sourceElementId: 'inv_001',
    name: 'Tomat',
    variety: 'San Marzano',
    status: 'afsluttet',
    location: 'Drivhus',
    sowDate: '2025-04-02',
    plantingOutDate: '2025-05-20',
    firstHarvestDate: '2025-08-01',
    quantity: 6,
    imageIds: [],
    logIds: [],
    guideId: 'guide_tomat',
    isArchived: true,
    archivedAt: '2025-10-30T00:00:00Z',
    archivedYear: 2025,
    createdAt: '2025-04-02T10:00:00Z',
    updatedAt: '2025-10-30T10:00:00Z',
  },
]

// ============================================
// Dyrkningslog
// ============================================

export const MOCK_LOGS: PlantLog[] = [
  {
    id: 'log_001',
    plantId: 'plant_001',
    userId: MOCK_USER_ID,
    date: '2026-03-10',
    type: 'sowing',
    title: 'Sået i forspiringsbakke',
    note: '6 frø i Jiffy-potter, stillet på vindueskarm.',
    imageIds: [],
    createdAt: '2026-03-10T10:00:00Z',
    updatedAt: '2026-03-10T10:00:00Z',
  },
  {
    id: 'log_002',
    plantId: 'plant_001',
    userId: MOCK_USER_ID,
    date: '2026-03-18',
    type: 'germination',
    title: 'Spiret',
    note: '5 ud af 6 er spiret. En enkelt er for langsom.',
    imageIds: [],
    createdAt: '2026-03-18T10:00:00Z',
    updatedAt: '2026-03-18T10:00:00Z',
  },
  {
    id: 'log_003',
    plantId: 'plant_001',
    userId: MOCK_USER_ID,
    date: '2026-05-15',
    type: 'planting_out',
    title: 'Udplantet i drivhus',
    note: 'Plantet i 40 cm afstand.',
    imageIds: [],
    createdAt: '2026-05-15T10:00:00Z',
    updatedAt: '2026-05-15T10:00:00Z',
  },
  {
    id: 'log_004',
    plantId: 'plant_002',
    userId: MOCK_USER_ID,
    date: '2026-03-15',
    type: 'sowing',
    title: 'Sået i bakke',
    note: '4 frø med bundvarme.',
    imageIds: [],
    createdAt: '2026-03-15T10:00:00Z',
    updatedAt: '2026-03-15T10:00:00Z',
  },
  {
    id: 'log_005',
    plantId: 'plant_002',
    userId: MOCK_USER_ID,
    date: '2026-04-08',
    type: 'germination',
    title: 'Spiret',
    note: 'Alle 4 er spiret efter 24 dage.',
    imageIds: [],
    createdAt: '2026-04-08T10:00:00Z',
    updatedAt: '2026-04-08T10:00:00Z',
  },
  {
    id: 'log_006',
    plantId: 'plant_003',
    userId: MOCK_USER_ID,
    date: '2026-03-28',
    type: 'sowing',
    title: 'Sået direkte',
    note: 'Sået i højbed, lige række med 10 cm afstand.',
    imageIds: [],
    createdAt: '2026-03-28T10:00:00Z',
    updatedAt: '2026-03-28T10:00:00Z',
  },
]

// ============================================
// Kalender
// ============================================

function today(offset = 0): string {
  const d = new Date('2026-04-24')
  d.setDate(d.getDate() + offset)
  return d.toISOString().split('T')[0]
}

export const MOCK_CALENDAR_TASKS: CalendarTask[] = [
  {
    id: 'task_001',
    userId: MOCK_USER_ID,
    title: 'Vand tomater i drivhus',
    description: 'Jord er ved at være tør. Vand godt igennem.',
    date: today(0),
    dueDate: today(0),
    taskType: 'watering',
    priority: 'high',
    status: 'open',
    source: 'plant',
    sourceId: 'plant_001',
    linkedPlantId: 'plant_001',
    isRecurring: false,
    createdAt: today(-1) + 'T00:00:00Z',
    updatedAt: today(-1) + 'T00:00:00Z',
  },
  {
    id: 'task_002',
    userId: MOCK_USER_ID,
    title: 'Omplant jalapeño',
    description: 'Planter er store nok til at komme i egen potte.',
    date: today(0),
    dueDate: today(0),
    taskType: 'repot',
    priority: 'critical',
    status: 'open',
    source: 'plant',
    sourceId: 'plant_002',
    linkedPlantId: 'plant_002',
    isRecurring: false,
    createdAt: today(-3) + 'T00:00:00Z',
    updatedAt: today(-3) + 'T00:00:00Z',
  },
  {
    id: 'task_003',
    userId: MOCK_USER_ID,
    title: 'Tjek spiring på Rapini',
    date: today(2),
    dueDate: today(2),
    taskType: 'pest_check',
    priority: 'medium',
    status: 'open',
    source: 'plant',
    sourceId: 'plant_003',
    linkedPlantId: 'plant_003',
    isRecurring: false,
    createdAt: today(-2) + 'T00:00:00Z',
    updatedAt: today(-2) + 'T00:00:00Z',
  },
  {
    id: 'task_004',
    userId: MOCK_USER_ID,
    title: 'Udplant tomater',
    description: 'Efter risiko for nattefrost.',
    date: today(15),
    dueDate: today(20),
    taskType: 'plant_out',
    priority: 'high',
    status: 'open',
    source: 'guide',
    sourceId: 'guide_tomat',
    linkedPlantId: 'plant_001',
    linkedGuideId: 'guide_tomat',
    isRecurring: false,
    createdAt: today(-14) + 'T00:00:00Z',
    updatedAt: today(-14) + 'T00:00:00Z',
  },
  {
    id: 'task_005',
    userId: MOCK_USER_ID,
    title: 'Luge højbed 2',
    date: today(-2),
    dueDate: today(-2),
    taskType: 'weeding',
    priority: 'low',
    status: 'open',
    source: 'manual',
    isRecurring: false,
    createdAt: today(-5) + 'T00:00:00Z',
    updatedAt: today(-5) + 'T00:00:00Z',
  },
]

// ============================================
// Generelle haveopgaver (årshjul)
// ============================================

export const MOCK_GENERAL_TASKS: GeneralGardenTask[] = [
  {
    id: 'gen_001',
    title: 'Forspir chili, aubergine og tomat',
    description: 'Chili og aubergine har lang udviklingstid — start allerede nu.',
    month: 2,
    category: 'forspiring',
    priority: 'medium',
    recurrence: 'yearly',
    sourceType: 'curated',
    linkedGuideIds: ['guide_chili', 'guide_tomat'],
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
  },
  {
    id: 'gen_002',
    title: 'Klargør jord og drivhus',
    description: 'Varm jorden op og luft ud. Tjek for huller i drivhus-plast.',
    month: 3,
    category: 'klargoering',
    priority: 'medium',
    recurrence: 'yearly',
    sourceType: 'curated',
    linkedGuideIds: [],
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
  },
  {
    id: 'gen_003',
    title: 'Prikl ud, så direkte, begynd hærdning',
    description: 'April er månedens store rutsjebane — alt sker samtidig.',
    month: 4,
    category: 'saaning',
    priority: 'high',
    recurrence: 'yearly',
    sourceType: 'curated',
    linkedGuideIds: [],
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
  },
  {
    id: 'gen_004',
    title: 'Udplant frostfølsomme planter',
    description: 'Efter isdamerne (midt-slut maj) kan tomater, agurker og chili ud.',
    month: 5,
    category: 'udplantning',
    priority: 'high',
    recurrence: 'yearly',
    sourceType: 'curated',
    linkedGuideIds: [],
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
  },
  {
    id: 'gen_005',
    title: 'Vand, gød og bind planter op',
    description: 'Juni er væksttid — regelmæssig pleje er alt.',
    month: 6,
    category: 'vedligehold',
    priority: 'medium',
    recurrence: 'yearly',
    sourceType: 'curated',
    linkedGuideIds: [],
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
  },
  {
    id: 'gen_006',
    title: 'Høst og vedligehold',
    description: 'Juli-august er høsttid. Pluk ofte for at holde planterne i produktion.',
    month: 7,
    category: 'hoest',
    priority: 'medium',
    recurrence: 'yearly',
    sourceType: 'curated',
    linkedGuideIds: [],
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
  },
  {
    id: 'gen_007',
    title: 'Saml frø til næste år',
    description: 'August er perfekt tid til at gemme frø fra dine bedste planter.',
    month: 8,
    category: 'froesamling',
    priority: 'low',
    recurrence: 'yearly',
    sourceType: 'curated',
    linkedGuideIds: [],
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
  },
  {
    id: 'gen_008',
    title: 'Plant forårsløg og del stauder',
    description: 'September er den bedste måned til løg — og staudedeling.',
    month: 9,
    category: 'plantning',
    priority: 'medium',
    recurrence: 'yearly',
    sourceType: 'curated',
    linkedGuideIds: [],
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
  },
  {
    id: 'gen_009',
    title: 'Plant træer og buske',
    description: 'Oktober er træ-plantnings-måneden. Jorden er varm og fugtig.',
    month: 10,
    category: 'plantning',
    priority: 'low',
    recurrence: 'yearly',
    sourceType: 'curated',
    linkedGuideIds: [],
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
  },
  {
    id: 'gen_010',
    title: 'Vinterklargøring',
    description: 'Tøm krukker, dæk følsomme planter, rens værktøj.',
    month: 11,
    category: 'vinterklargoering',
    priority: 'medium',
    recurrence: 'yearly',
    sourceType: 'curated',
    linkedGuideIds: [],
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
  },
  {
    id: 'gen_011',
    title: 'Planlæg næste sæson',
    description: 'December er planlægningsmåned. Gennemgå frøbank, bestil nyt.',
    month: 12,
    category: 'planlaegning',
    priority: 'low',
    recurrence: 'yearly',
    sourceType: 'curated',
    linkedGuideIds: [],
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
  },
  {
    id: 'gen_012',
    title: 'Planlæg sæson, gennemgå frø',
    description: 'Januar er rolig — perfekt til at drømme og bestille.',
    month: 1,
    category: 'planlaegning',
    priority: 'low',
    recurrence: 'yearly',
    sourceType: 'curated',
    linkedGuideIds: [],
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
  },
]

// ============================================
// Dyrkningsguides (med arts/sorts-hierarki)
// ============================================

export const MOCK_GUIDES: Guide[] = [
  // Artsguide: Tomat
  {
    id: 'guide_tomat',
    plantName: 'Tomat',
    variety: null,
    latinName: 'Solanum lycopersicum',
    guideLevel: 'species',
    parentGuideId: null,
    primaryCategoryId: 'fro',
    subcategoryId: 'groentsager',
    summary: 'Tomater forspires indendørs i marts-april og udplantes efter risiko for nattefrost. Trives bedst i drivhus, men friland virker også.',
    difficulty: 'medium',
    tags: ['drivhus', 'forkultivering', 'spiselig', 'klassiker'],
    quickFacts: {
      preCultivation: true,
      sowingMonths: [3, 4],
      directSowingMonths: [],
      plantingOutMonths: [5, 6],
      harvestMonths: [7, 8, 9],
      light: 'full_sun',
      water: 'regular',
      soil: 'Næringsrig, veldrænet',
      germinationTemperature: '20-25°C',
      germinationDays: '7-14',
      plantSpacing: '40-60 cm',
      rowSpacing: '60-80 cm',
      sowingDepthMm: 5,
      frostSensitive: true,
      minimumTemperature: '10°C',
    },
    sections: [
      {
        key: 'intro',
        title: 'Introduktion',
        body: 'Tomaten er en af de mest populære dyrkningsplanter i danske haver. Den trives i drivhus, men de hårdføre sorter klarer sig også på friland — særligt i varme, solrige somre.',
      },
      {
        key: 'pre_cultivation',
        title: 'Forspiring',
        body: 'Så frø 5 mm dybt i forspiringsjord fra midt-marts til start af april. Hold 20-25°C for hurtig spiring (7-14 dage). Placer lyst når spirerne er oppe.',
      },
      {
        key: 'planting_out',
        title: 'Udplantning',
        body: 'Efter risiko for nattefrost, typisk midt-maj. Hærd planterne et par dage på et skyggested. Plant dybt — tomater skyder nye rødder fra stænglen.',
      },
      {
        key: 'care',
        title: 'Pasning',
        body: 'Vand regelmæssigt ved jordoverfladen, aldrig på bladene. Gød med tomatgødning hver 1-2 uger. Knib sideskud på busktomater. Bind op til pinde eller snor.',
      },
      {
        key: 'pests',
        title: 'Skadedyr og sygdomme',
        body: 'Kartoffelskimmel er den største trussel — hold bladene tørre. Tomatsværmer, bladlus og hvide fluer kan forekomme i drivhus.',
      },
      {
        key: 'harvest',
        title: 'Høst',
        body: 'Fra juli til frosten kommer. Plukkes når frugten er fuldt farvet. Grønne tomater kan eftermodne indendørs.',
      },
      {
        key: 'mistakes',
        title: 'Typiske fejl',
        body: 'For tidlig udplantning (nattefrost), for meget vand i starten (kan give gule blade), manglende afkortning af sideskud, gødning med for meget kvælstof (mange blade, få frugter).',
      },
    ],
    calendarRules: [
      { taskType: 'pre_sow', title: 'Forspir tomat', recommendedMonths: [3, 4], priority: 'high' },
      { taskType: 'repot', title: 'Omplant tomat', trigger: 'sowingDate', relativeOffsetDays: 28, priority: 'medium' },
      { taskType: 'plant_out', title: 'Udplant tomat', recommendedMonths: [5, 6], condition: 'after_last_frost', priority: 'high' },
      { taskType: 'harvest', title: 'Høst tomater', recommendedMonths: [7, 8, 9], priority: 'medium' },
    ],
    mediaIds: [],
    sourceLinks: [],
    status: 'published',
    visibility: 'system',
    reviewStatus: 'approved',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-04-01T00:00:00Z',
  },
  // Sortsguide: Tomat, San Marzano (override på artsguide)
  {
    id: 'guide_tomat_san_marzano',
    plantName: 'Tomat',
    variety: 'San Marzano',
    latinName: 'Solanum lycopersicum "San Marzano"',
    guideLevel: 'variety',
    parentGuideId: 'guide_tomat',
    primaryCategoryId: 'fro',
    subcategoryId: 'groentsager',
    summary: 'San Marzano er den klassiske italienske saucetomat. Aflang, fast, næsten frøfri. Kræver drivhus eller varmt fritliggende sted.',
    difficulty: 'medium',
    tags: ['drivhus', 'sauce', 'italiensk', 'heirloom'],
    quickFacts: {
      // Arver det meste fra artsguiden — kun overrides her
      sowingMonths: [3, 4],
      directSowingMonths: [],
      plantingOutMonths: [5, 6],
      harvestMonths: [8, 9],          // Lidt senere end almindelig tomat
      plantSpacing: '50-60 cm',
      rowSpacing: '70-80 cm',
    },
    sections: [
      {
        key: 'intro',
        title: 'Om San Marzano',
        body: 'Italiensk klassiker og moderen til al god tomatsauce. Voksekraftig, høj busk der skal bindes godt op. Mere krævende til varme end almindelige tomater.',
      },
    ],
    calendarRules: [],
    mediaIds: [],
    sourceLinks: [],
    status: 'published',
    visibility: 'system',
    reviewStatus: 'approved',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-04-01T00:00:00Z',
  },
  // Artsguide: Chili
  {
    id: 'guide_chili',
    plantName: 'Chili',
    variety: null,
    latinName: 'Capsicum',
    guideLevel: 'species',
    parentGuideId: null,
    primaryCategoryId: 'fro',
    subcategoryId: 'groentsager',
    summary: 'Chili har lang udviklingstid og skal forspires tidligt. Kræver varme, sol og tålmodighed.',
    difficulty: 'medium',
    tags: ['drivhus', 'krydderi', 'varmt'],
    quickFacts: {
      preCultivation: true,
      sowingMonths: [1, 2, 3],
      directSowingMonths: [],
      plantingOutMonths: [5, 6],
      harvestMonths: [8, 9, 10],
      light: 'full_sun',
      water: 'regular',
      germinationTemperature: '22-28°C',
      germinationDays: '10-21',
      plantSpacing: '40-50 cm',
      sowingDepthMm: 5,
      frostSensitive: true,
    },
    sections: [
      {
        key: 'intro',
        title: 'Introduktion',
        body: 'Chili elsker varme og sol. Den lange spiringstid og udviklingsperiode gør, at du skal i gang allerede i januar-februar hvis du vil have modne frugter før frosten.',
      },
      {
        key: 'pre_cultivation',
        title: 'Forspiring',
        body: 'Så i januar-februar med bundvarme for at sikre hurtig spiring. Chilifrø kan være lunefuld — dæk bakken med plastfilm for at holde fugten.',
      },
    ],
    calendarRules: [
      { taskType: 'pre_sow', title: 'Forspir chili', recommendedMonths: [1, 2, 3], priority: 'high' },
      { taskType: 'repot', title: 'Omplant chili', trigger: 'sowingDate', relativeOffsetDays: 28, priority: 'medium' },
      { taskType: 'plant_out', title: 'Udplant chili', recommendedMonths: [5, 6], condition: 'after_last_frost', priority: 'high' },
    ],
    mediaIds: [],
    sourceLinks: [],
    status: 'published',
    visibility: 'system',
    reviewStatus: 'approved',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-01T00:00:00Z',
  },
  // Artsguide: Basilikum
  {
    id: 'guide_basilikum',
    plantName: 'Basilikum',
    variety: null,
    latinName: 'Ocimum basilicum',
    guideLevel: 'species',
    parentGuideId: null,
    primaryCategoryId: 'fro',
    subcategoryId: 'krydderurter',
    summary: 'Duftende kryddure der elsker sol og varme. Fås i mange varianter — fra søde italienske til citron- og thai-varianter.',
    difficulty: 'easy',
    tags: ['krydderurt', 'sommer', 'vindueskarm'],
    quickFacts: {
      preCultivation: true,
      sowingMonths: [3, 4, 5],
      directSowingMonths: [5, 6],
      plantingOutMonths: [5, 6],
      harvestMonths: [6, 7, 8, 9],
      light: 'full_sun',
      water: 'regular',
      sowingDepthMm: 0,        // Lys-spire — sås på overfladen
      germinationDays: '5-10',
      plantSpacing: '20-25 cm',
      frostSensitive: true,
    },
    sections: [
      {
        key: 'intro',
        title: 'Introduktion',
        body: 'Basilikum er årets nemmeste krydderurt hvis man husker to ting: lys og varme.',
      },
      {
        key: 'sowing',
        title: 'Såning',
        body: 'Basilikumfrø er lys-spirere. Sås på overfladen af fugtig jord — pres let ned, dæk ikke med jord. Hold 20°C+ for hurtig spiring.',
      },
    ],
    calendarRules: [
      { taskType: 'sowing', title: 'Så basilikum', recommendedMonths: [3, 4, 5], priority: 'low' },
    ],
    mediaIds: [],
    sourceLinks: [],
    status: 'published',
    visibility: 'system',
    reviewStatus: 'approved',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-02-01T00:00:00Z',
  },
]

// ============================================
// Community
// ============================================

export const MOCK_GROUPS: CommunityGroup[] = [
  {
    id: 'grp_tomater',
    title: 'Tomater',
    description: 'Alt om tomatdyrkning i Danmark — fra forspiring til frøsamling.',
    slug: 'tomater',
    groupLevel: 'category',
    linkedPlantName: 'Tomat',
    memberCount: 248,
    isReadOnly: false,
    createdAt: '2025-01-15T00:00:00Z',
    updatedAt: '2026-04-20T00:00:00Z',
  },
  {
    id: 'grp_chili',
    title: 'Chili-dyrkere',
    description: 'Chili, habanero, jalapeño — vi deler sorter og erfaringer.',
    slug: 'chili',
    groupLevel: 'category',
    linkedPlantName: 'Chili',
    memberCount: 134,
    isReadOnly: false,
    createdAt: '2025-02-01T00:00:00Z',
    updatedAt: '2026-04-18T00:00:00Z',
  },
  {
    id: 'grp_drivhus',
    title: 'Drivhus-dyrkning',
    description: 'Tips til det opvarmede eller uopvarmede drivhus.',
    slug: 'drivhus',
    groupLevel: 'theme',
    memberCount: 89,
    isReadOnly: false,
    createdAt: '2025-03-10T00:00:00Z',
    updatedAt: '2026-04-15T00:00:00Z',
  },
]

export const MOCK_MEMBERSHIPS: CommunityMembership[] = [
  {
    id: 'mem_001',
    groupId: 'grp_tomater',
    userId: MOCK_USER_ID,
    role: 'member',
    invitedAt: '2026-04-01T00:00:00Z',
    joinedAt: '2026-04-02T00:00:00Z',
    createdAt: '2026-04-01T00:00:00Z',
  },
]

// ============================================
// Idétavle
// ============================================

export const MOCK_IDEAS: Idea[] = [
  {
    id: 'idea_001',
    userId: MOCK_USER_ID,
    title: 'Anlæg ny urtehave ved køkkendør',
    description: 'Små krydderurter tæt på køkkenet. Timian, rosmarin, oregano, salvie.',
    imageIds: [],
    tags: ['urtehave', 'projekt'],
    status: 'planning',
    targetYear: 2026,
    createdAt: '2026-03-01T00:00:00Z',
    updatedAt: '2026-04-10T00:00:00Z',
  },
  {
    id: 'idea_002',
    userId: MOCK_USER_ID,
    title: 'Plant et figentræ',
    description: 'Gerne en dansk-hårdfør sort som Brown Turkey. Mod syd-mur.',
    imageIds: [],
    tags: ['traeer', 'frugt'],
    status: 'idea',
    targetYear: 2027,
    createdAt: '2026-04-15T00:00:00Z',
    updatedAt: '2026-04-15T00:00:00Z',
  },
  {
    id: 'idea_003',
    userId: MOCK_USER_ID,
    title: 'Byg uopvarmet drivhus',
    description: 'Udvid sæsonen — forspiring i tidlig marts, sent efterår.',
    imageIds: [],
    tags: ['drivhus', 'stor-projekt'],
    status: 'idea',
    targetYear: 2027,
    createdAt: '2026-02-20T00:00:00Z',
    updatedAt: '2026-02-20T00:00:00Z',
  },
]

// ============================================
// Notifikationer
// ============================================

export const MOCK_NOTIFICATION_PREFS: NotificationPreference = {
  userId: MOCK_USER_ID,
  pushEnabled: true,
  dailyDigestEnabled: true,
  criticalOnly: false,
  quietHours: { start: '20:00', end: '08:00' },
}

// ============================================
// Progress / gamification
// ============================================

export const MOCK_PROGRESS: ProgressState = {
  userId: MOCK_USER_ID,
  period: '2026-04',
  completedTasks: 14,
  totalTasks: 22,
  criticalTasksCompleted: 3,
  criticalTasksTotal: 4,
  visualState: 'basket_60_percent',
}

// ============================================
// Medier (tom i første iteration)
// ============================================

export const MOCK_MEDIA: MediaAsset[] = []

// ============================================
// Custom underkategorier (brugerskabte)
// ============================================

export const MOCK_CUSTOM_SUBCATEGORIES: Subcategory[] = [
  {
    id: 'custom_drivhusfavoritter',
    name: 'Drivhusfavoritter',
    parentCategoryIds: ['fro'],
    isSystem: false,
    createdByUserId: MOCK_USER_ID,
    createdAt: '2026-03-20T00:00:00Z',
  },
]
